services:
  postgresql:
    container_name: "postgres.hrag"
    image: ankane/pgvector
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer
      DATABASES: hrag
    volumes:
      - ./data/postgresql/:/docker-entrypoint-initdb.d

  neo4j:
    container_name: "neo4j.hrag"
    image: bitnami/neo4j:latest
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    environment:
      - NEO4J_PASSWORD=password
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
    volumes:
      - ./data/neo4j:/bitnami
      - ./data/neo4j/plugins:/plugins
      - ./data/neo4j/neo4j.conf:/opt/bitnami/neo4j/conf/neo4j.conf
  api:
    container_name: "api.hrag"
    build:
      context: "api/"
      dockerfile: docker/Dockerfile
    depends_on:
      - postgresql
      - neo4j
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH="./:$PYTHONPATH"
      - POSTGRESQL_URL=postgresql+psycopg2://developer:developer@postgres.hrag:5432/hrag
      - NEO4J_URL=bolt://neo4j.hrag:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password
      - DEFAULT_LLM_ENDPOINT=http://host.docker.internal:11434
      - DEFAULT_LLM_API_KEY=""
      - DEFAULT_LLM_MODEL=llama3.1:8b
      - DEFAULT_EMBEDDING_MODEL=nomic-embed-text:latest
      - CREATE_TENANT_IF_NOT_EXISTS=true
    volumes:
      - ./api:/app
