"""init migration

Revision ID: 09ff2f327925
Revises:
Create Date: 2024-09-13 10:42:30.351486

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "09ff2f327925"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenant",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant", sa.Unicode(length=128), nullable=False),
        sa.Column(
            "provider",
            sa.Enum("ollama", "open_ai", name="languagemodelprovider"),
            nullable=False,
        ),
        sa.Column("provider_endpoint", sa.Unicode(length=1024), nullable=True),
        sa.Column("provider_api_key", sa.Unicode(length=1024), nullable=True),
        sa.Column("llm_model", sa.Unicode(length=128), nullable=True),
        sa.Column("embedding_model", sa.Unicode(length=128), nullable=True),
        sa.Column("enable_summary_embedding", sa.Boolean(), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column(
            "created_dt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_dt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tenant_enable_summary_embedding"),
        "tenant",
        ["enable_summary_embedding"],
        unique=False,
    )
    op.create_index(op.f("ix_tenant_id"), "tenant", ["id"], unique=True)
    op.create_index(op.f("ix_tenant_status"), "tenant", ["status"], unique=False)
    op.create_index(op.f("ix_tenant_tenant"), "tenant", ["tenant"], unique=True)
    op.create_table(
        "user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.Unicode(length=35), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "chat_history", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("chat_summary", sa.UnicodeText(), nullable=True),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column(
            "created_dt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_dt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username", "tenant_id"),
    )
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=True)
    op.create_index(op.f("ix_user_status"), "user", ["status"], unique=False)
    op.create_index(op.f("ix_user_tenant_id"), "user", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_tenant_id"), table_name="user")
    op.drop_index(op.f("ix_user_status"), table_name="user")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_tenant_tenant"), table_name="tenant")
    op.drop_index(op.f("ix_tenant_status"), table_name="tenant")
    op.drop_index(op.f("ix_tenant_id"), table_name="tenant")
    op.drop_index(op.f("ix_tenant_enable_summary_embedding"), table_name="tenant")
    op.drop_table("tenant")

    sa.Enum("ollama", "open_ai", name="languagemodelprovider").drop(op.get_bind())
    # ### end Alembic commands ###
